### ISSUE TITLE
error:  plugin version or a dependancy of this plugin is not on npm!

### ISSUE THREAD

**Issue by LOG-TAG** [cesarvr/pdf-generator-example#1]
> Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: com.html2pdf.generator@~0.9.8
how to fix this ? (new to phone gap)

**Comment by cesarvr** [comment]
This happens because the installer of version 1.0.8 the config.xml was outdated, you just need to go to your config.xml (is in your root folder) remove the entry `<plugin name="com.html2pdf.generator" spec="~0.9.8" />` , then just reinstall `cordova plugin add cordova-pdf-generator --save`, that should fix it.

**Comment by LOG-TAG** [comment]
Thanks for the plug-in :100:   I was using npm version old , my bad !
